### ISSUE TITLE
Difference with xiaomi_airpurifier

### ISSUE THREAD

**Issue by watermarkhu** [syssi/xiaomi_fan#133]
Hello @syssi,

I would like to ask the difference between this component and the [xiaomi_airpurifier](https://github.com/syssi/xiaomi_airpurifier) component. It seems that all features of xiaomi_fan are included in xiaomi_airpurifier. Moreover, xiaomi_airpurifier is already included in the HACS directory, whereas xiaomi_fan has to be added as a custom directory. 

However, it seems that xiaomi_fan has more commits related to fixing fan-related issues. Is your plan to deprecate xiaomi_fan in the future in favor for an unified custom integration?

**Comment by BlueSoD** [comment]
i would actually like to know this aswell, and also will both of these be integrated into the official xiaomi integration?

**Comment by syssi** [comment]
Good question. Unfortunately I cannot provide good answers because there is no concrete plan. At the moment I maintain both custom components (airpurifier & fan). Every now an then I merge some fan features of xiaomi_fan into xiaomi_airpurifier. In the past I've used the airpurifier custom component as "beta version" (staging). As soon the new version looks stable I tried to contribute the changes to the HA core. At the moment the last step is blocked because of some blocking issues. Some day all `xiaomi_miio_*` components will be merged into a big xiaomi_miio platform.

**Comment by watermarkhu** [comment]
So `xiaomi_fan` will always contain the most features and fixes related to fans, until the point it is deprecated when the big merge occurs. Thanks for clarifying this. Might I suggest to put the above explanation in the readme of `xiaomi_fan`?

**Comment by syssi** [comment]
Good summary! I will extend the README.
