### ISSUE TITLE
zhimi.fan.za5 mode reversed

### ISSUE THREAD

**Issue by spitz66** [syssi/xiaomi_fan#147]
First of all thanks for your work!

I'm using Smartmi Standing Fan 3 (zhimi.fan.za5), but I find that the mode is reversed compared to when looking at fan display.
It has two modes normal/nature and when fan is in "nature" mode it shows as below in Home Assistant:
![image](https://user-images.githubusercontent.com/65921206/123310534-77c7fa00-d526-11eb-8276-47768ccafa94.png)

Not a big deal to reverse in config but worth mentioning.

**Comment by filikun** [comment]
Yeah I just got my fan to work and I'm having the same issue. `xiaomi_miio_fan: fan_set_natural_mode_off` does turn it on instead of off and reversed. 

Also `oscillation_angle` not working, the attrbiute returns null. I guess if we could get the temp, battery, humidity as well it would be a nice bonus.

**Comment by syssi** [comment]
Let's close this. Please subscribe #151.
