### ISSUE TITLE
Platform xiaomi_miio_fan not ready yet. Retrying in 30 seconds.

### ISSUE THREAD

**Issue by TribuneX** [syssi/xiaomi_fan#22]
I am using 0.78.0 with your custom component. It worked for some days, but now I get the following error in the hass log:
`Platform xiaomi_miio_fan not ready yet. Retrying in 30 seconds.`

Together with:
`Unable to discover a device at address 192.168.178.28`

miiocli works sometimes:

`bash-4.4# miiocli fansa1 --ip  192.168.178.28 --token <token> info
Model: zhimi.fan.sa1
Hardware version: ESP32
Firmware version: 1.3.1
Network: {'localIp': '192.168.178.28', 'mask': '255.255.255.0', 'gw': '192.168.178.1'}
AP: {'rssi': -61, 'ssid': 'Home', 'primary': 11, 'bssid': '38:10:D5:B1:28:F2'}`

But usually results in:
`bash-4.4# miiocli fansa1 --ip  192.168.178.28 --token <token> info
ERROR:miio.device:Unable to discover a device at address 192.168.178.28
Error: Unable to discover the device 192.168.178.28`

**Comment by kikamoo** [comment]
fan sa1 connection in the HA is unstable too in my home. 
in almost every few minutes, log shows "Unable to discover a device at address~"
However other xiaomis like mi air2, humidifier2, gateway are all right without warning logs.

**Comment by spbear** [comment]
I also have the same problem with zhimi.fan.sa1.
When I ping to the device. It can observe packet loss is happened.
I think this is a root cause of my problem.

` $ ping 192.168.1.84`
`
PING 192.168.1.84 (192.168.1.84) 56(84) bytes of data.
`
`64 bytes from 192.168.1.84: icmp_seq=1 ttl=255 time=85.2 ms`
`64 bytes from 192.168.1.84: icmp_seq=2 ttl=255 time=3.40 ms`
`64 bytes from 192.168.1.84: icmp_seq=3 ttl=255 time=3.85 ms`
`64 bytes from 192.168.1.84: icmp_seq=4 ttl=255 time=3.62 ms`
`64 bytes from 192.168.1.84: icmp_seq=6 ttl=255 time=1057 ms`
`64 bytes from 192.168.1.84: icmp_seq=7 ttl=255 time=19.4 ms`
`64 bytes from 192.168.1.84: icmp_seq=8 ttl=255 time=3.43 ms`
`64 bytes from 192.168.1.84: icmp_seq=9 ttl=255 time=3.47 ms`
`64 bytes from 192.168.1.84: icmp_seq=10 ttl=255 time=1080 ms`
`64 bytes from 192.168.1.84: icmp_seq=11 ttl=255 time=9.36 ms`
`--- 192.168.1.84 ping statistics ---`
`11 packets transmitted, 10 received, 9% packet loss, time 10198ms`
`rtt min/avg/max/mdev = 3.407/227.024/1080.529/421.785 ms, pipe 2`

Even though a problem is observed with Home Assistant, there is no problem with Mi Home smartphone application at all.
Is there a way to mitigate this problem?

**Comment by syssi** [comment]
This isn't an issue of the custom component.

**Comment by woinkeyman** [comment]
Hi - ran into the same issue - 

Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds.
10:05 PM helpers/entity_platform.py (WARNING) - message first occurred at 9:49 PM and shows up 6 times
Unable to discover a device at address 10.123.8.167
10:05 PM custom_components/xiaomi_miio_fan/fan.py (ERROR) - message first occurred at 9:40 PM and shows up 6 times
Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
10:02 PM __main__.py (WARNING) - message first occurred at 9:40 PM and shows up 9 times
Got error when receiving: timed out
10:02 PM custom_components/xiaomi_miio_fan/fan.py (ERROR) - message first occurred at 9:41 PM and shows up 5 times

this is preventing the platform from working at all - any chance there are parts of the custom component i can fix? other components are fine contacting local IP addresses too.
