### ISSUE TITLE
Add dmaker.fan.p8 support

### ISSUE THREAD

**Issue by BearD01001** [syssi/xiaomi_fan#82]
Could you support of dmaker.fan.p8, please?

Thank you very much! 🙏🏼

**Comment by hokagegano** [comment]
Same for me 👍

**Comment by mon3y78** [comment]
Same for me!!!

**Comment by janfajessen** [comment]
I find this miot-spec, I change the 1c suffix for my model name p8 because are the same, maybe this will be helpful for the programer:

{
type: "urn:miot-spec-v2:device:fan:0000A005:dmaker-p8:1",
description: "Fan",
services: [
{
iid: 1,
type: "urn:miot-spec-v2:service:device-information:00007801:dmaker-p8:1",
description: "Device Information",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property:manufacturer:00000001:dmaker-p8:1",
description: "Device Manufacturer",
format: "string",
access: [
"read"
]
},
{
iid: 2,
type: "urn:miot-spec-v2:property:model:00000002:dmaker-p8:1",
description: "Device Model",
format: "string",
access: [
"read"
]
},
{
iid: 3,
type: "urn:miot-spec-v2:property:serial-number:00000003:dmaker-p8:1",
description: "Device Serial Number",
format: "string",
access: [
"read"
]
},
{
iid: 4,
type: "urn:miot-spec-v2:property:firmware-revision:00000005:dmaker-p8:1",
description: "Current Firmware Version",
format: "string",
access: [
"read"
]
}
]
},
{
iid: 2,
type: "urn:miot-spec-v2:service:fan:00007808:dmaker-p8:1",
description: "Fan",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property🔛00000006:dmaker-p8:1",
description: "Switch Status",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 2,
type: "urn:miot-spec-v2:property:fan-level:00000016:dmaker-p8:1",
description: "Fan Level",
format: "uint8",
access: [
"read",
"write",
"notify"
],
unit: "none",
value-list: [
{
value: 1,
description: "1"
},
{
value: 2,
description: "2"
},
{
value: 3,
description: "3"
}
]
},
{
iid: 3,
type: "urn:miot-spec-v2:property:horizontal-swing:00000017:dmaker-p8:1",
description: "Horizontal Swing",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 7,
type: "urn:miot-spec-v2:property:mode:00000008:dmaker-p8:1",
description: "Mode",
format: "uint8",
access: [
"read",
"write",
"notify"
],
unit: "none",
value-list: [
{
value: 0,
description: "Straight Wind"
},
{
value: 1,
description: "Sleep"
}
]
},
{
iid: 10,
type: "urn:miot-spec-v2:property:off-delay-time:00000054:dmaker-p8:1",
description: "Power Off Delay Time",
format: "uint16",
access: [
"read",
"write",
"notify"
],
unit: "minutes",
value-range: [
0,
480,
1
]
},
{
iid: 11,
type: "urn:miot-spec-v2:property:alarm:00000012:dmaker-p8:1",
description: "Alarm",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 12,
type: "urn:miot-spec-v2:property:brightness:0000000D:dmaker-p8:1",
description: "Brightness",
format: "bool",
access: [
"read",
"write",
"notify"
],
unit: "none"
}
],
actions: [
{
iid: 1,
type: "urn:miot-spec-v2:action:toggle:00002811:dmaker-p8:1",
description: "Toggle",
in: [ ],
out: [ ]
}
]
},
{
iid: 3,
type: "urn:miot-spec-v2:service:physical-controls-locked:00007807:dmaker-p8:1",
description: "Physical Control Locked",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property:physical-controls-locked:0000001D:dmaker-p8:1",
description: "Physical Control Locked",
format: "bool",
access: [
"read",
"write",
"notify"
]
}
]
}
]
}

**Comment by Rrapa** [comment]
Any luck with adding support for dmaker.fan.p8 by chance?

**Comment by syssi** [comment]
First step: https://github.com/rytilahti/python-miio/pull/883

I will implement the device at this custom component: https://github.com/syssi/xiaomi_airpurifier/

**Comment by syssi** [comment]
As long this device isn't supported natively you can use `dmaker.fan.c1` because the specs are equal.
